version: '3.7'
services:
  php:
    container_name: dev.local-prod
    image: 'defaultvalue/php:8.1-production'
    user: 'docker:docker'
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: always
    networks:
      default:
        aliases:
          - dev.local
          - www.dev.local
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.dev-local-http.rule=Host(`dev.local`,`www.dev.local`)'
      - traefik.http.routers.dev-local-http.entrypoints=http
      - traefik.http.routers.dev-local-http.service=dev-local-http
      - traefik.http.services.dev-local-http.loadbalancer.server.port=80
      - traefik.http.services.dev-local-http.loadbalancer.server.scheme=http
      - 'traefik.http.routers.dev-local-https.rule=Host(`dev.local`,`www.dev.local`)'
      - traefik.http.routers.dev-local-https.entrypoints=https
      - traefik.http.routers.dev-local-https.tls=true
      - traefik.http.routers.dev-local-https.service=dev-local-https
      - traefik.http.services.dev-local-https.loadbalancer.server.port=443
      - traefik.http.services.dev-local-https.loadbalancer.server.scheme=https
    environment:
      - COMPOSER_VERSION=2
    volumes:
      - '../../:/var/www/html'
      - '${DOCKERIZER_SSL_CERTIFICATES_DIR}:/certs'
      - './apache/virtual-host.conf:/etc/apache2/sites-enabled/000-default.conf:ro'
  mysql:
    image: 'mariadb:10.6'
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: magento_db
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    volumes:
      - 'mariadb_prod_data:/var/lib/mysql'
      - './mysql/my.cnf:/etc/mysql/conf.d/zzz-my.cnf:ro'
      - './mysql_initdb:/docker-entrypoint-initdb.d:ro'
  opensearch:
    image: 'magento/magento-cloud-docker-opensearch:2.5-1.3.5'
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - indices.query.bool.max_clause_count=10240
      - index.blocks.read_only_allow_delete
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - 'opensearch_prod_data:/usr/share/opensearch/data:rw'
  redis:
    image: 'redis:7.0'
    restart: always
volumes:
  mariadb_prod_data:
    external: false
  opensearch_prod_data:
    external: false
